FROM alpine as new-alpine
FROM php:8.0-fpm-alpine3.13 as prod

COPY configure.sh /
COPY php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf.d/php.prod.ini /usr/local/etc/php
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
COPY docker-dev-entrypoint /usr/local/bin
COPY conf.d/90-xdebug.ini /usr/local/etc/php/conf.d/

RUN apk add --no-cache $PHPIZE_DEPS \
        && pecl install xdebug-3.0.4 \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["php-fpm"]