ARG PHP_VERSION
FROM alpine as new-alpine
FROM php:${PHP_VERSION}-fpm-alpine3.16 as prod

COPY configure.sh /
COPY php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf.d/php.prod.ini /usr/local/etc/php
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

COPY docker-healthcheck /usr/local/bin/docker-healthcheck
RUN chmod +x /usr/local/bin/docker-healthcheck
HEALTHCHECK --interval=5s --timeout=3s --retries=3 CMD ["docker-healthcheck"]

RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
COPY docker-dev-entrypoint /usr/local/bin
COPY conf.d/90-xdebug.ini /usr/local/etc/php/conf.d/

RUN apk add --no-cache $PHPIZE_DEPS \
        && pecl install xdebug-3.1.2 \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS

FROM prod as prod-sqlsrv
COPY configure-sqlsrv.sh /
COPY conf.d/90-sqlsrv.ini /usr/local/etc/php/conf.d/
RUN /configure-sqlsrv.sh \
    && rm /configure-sqlsrv.sh

FROM dev as dev-sqlsrv
COPY configure-sqlsrv.sh /
COPY conf.d/90-sqlsrv.ini /usr/local/etc/php/conf.d/
RUN /configure-sqlsrv.sh \
    && rm /configure-sqlsrv.sh

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["php-fpm"]